apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-scale:0.2
        resources:
          requests:
            cpu: 200m
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
